/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bilsemedirne.bilsemyonetim.GUI;

import javax.swing.JFrame;
import org.opencv.core.Core;

/**
 *
 * @author serkancam
 */
public class AnaEkran extends javax.swing.JFrame {
 YeniKayitEkrani yke=null;
  static
    {
        System.load(System.getProperty("user.dir")+"\\opencv\\opencv_java249.dll");
        System.out.println(System.getProperty("user.dir")+"\\opencv\\opencv_java249.dll");
    }
    /**
     * Creates new form AnaEkran
     */
    public AnaEkran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        mIslemler = new javax.swing.JMenu();
        mYeniKayit = new javax.swing.JMenuItem();
        mYenileme = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        desktopPane.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.IconBorder iconBorder1 = new org.jdesktop.swingx.border.IconBorder();
        iconBorder1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bilsemedirne/bilsemyonetim/GUI/icons/bilsem-loo (1200x1066).jpg"))); // NOI18N
        desktopPane.setBorder(iconBorder1);

        mIslemler.setMnemonic('e');
        mIslemler.setText("Kayıt İşlemleri");
        mIslemler.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        mYeniKayit.setText("Yeni Kayıt");
        mYeniKayit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mYeniKayitActionPerformed(evt);
            }
        });
        mIslemler.add(mYeniKayit);

        mYenileme.setText("Kayıt Yenileme");
        mIslemler.add(mYenileme);

        menuBar.add(mIslemler);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mYeniKayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mYeniKayitActionPerformed
        // TODO add your handling code here:
       
        yke=new YeniKayitEkrani();
        desktopPane.add(yke);
        yke.setVisible(true );
        
                
        
    }//GEN-LAST:event_mYeniKayitActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        try
        {
            yke.myThread.runnable=false;
            yke.webSource.release();
                       
        } 
        catch (Exception e)
        {
            System.out.println("Direk kapatma hatası");
        }
       

      
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
   
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         //main method
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaEkran().setVisible(true);
            }
        });
        
         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu mIslemler;
    private javax.swing.JMenuItem mYeniKayit;
    private javax.swing.JMenuItem mYenileme;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
