/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bilsemedirne.bilsemyonetim.GUI;
import com.bilsemedirne.bilsemyonetim.ENTITY.*;
import com.bilsemedirne.bilsemyonetim.DAO.*;
import com.bilsemedirne.bilsemyonetim.Islem.Cift;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
        

/**
 *
 * @author serkancam
 */
public class VeliBilgisi extends javax.swing.JFrame
{
    byte veliHayattami;
    public int veliTipi=-1;
    int veliOgrenimDurumu=-1;
    String veliAd="",veliSoyad="",veliEposta="",veliEvTelefon="",
            veliIsTelefon="",veliCeptelefon="",veliMeslegi="",veliEvAdresi="",veliIsAdresi="";

    /**
     * Creates new form VeliBilgisi
     */
    public YeniKayitEkrani ataPencere;
    public VeliBilgisi()
    {
        initComponents();
    }
    void OgrenimDurumuCBDoldur()
    {
        
        List<OgrenimDurumu> ogrenimDurumlari =null;
      
       OgrenimDurumuDAO islem=new OgrenimDurumuDAO();
       ogrenimDurumlari=islem.TumOgrenimDurumlariGetir();
      
        for (OgrenimDurumu gelen : ogrenimDurumlari) 
        {            
            cbVeliOgrenimDurumu.addItem(new Cift(gelen.getOgrenimDurumuKodu(),gelen.getOgrenimDurumuAdi()));                        
           
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pnlVeliBilgileri = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txtVeliMeslegi = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtVeliIsTelefonu = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtVeliEvAdresi = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();
        cbVeliOgrenimDurumu = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtVeliIsAdresi = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        txtVeliCepTelefonu = new javax.swing.JTextField();
        txtVeliSoyadi = new javax.swing.JTextField();
        txtVeliAdi = new javax.swing.JTextField();
        txtVeliEvTelefonu = new javax.swing.JTextField();
        txtVeliEposta = new javax.swing.JTextField();
        btnKaydet = new javax.swing.JButton();
        btnIptal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlVeliBilgileri.setBorder(javax.swing.BorderFactory.createTitledBorder("Veli Bilgileri"));
        pnlVeliBilgileri.setPreferredSize(new java.awt.Dimension(450, 330));
        pnlVeliBilgileri.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setText("Adı:");
        jLabel21.setName("elleme"); // NOI18N
        pnlVeliBilgileri.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 60, 30));

        txtVeliMeslegi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtVeliMeslegi.setName("gizle"); // NOI18N
        pnlVeliBilgileri.add(txtVeliMeslegi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 145, 30));

        jLabel22.setText("Soyadı:");
        jLabel22.setName("elleme"); // NOI18N
        pnlVeliBilgileri.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 70, 30));

        txtVeliIsTelefonu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtVeliIsTelefonu.setName("gizle"); // NOI18N
        pnlVeliBilgileri.add(txtVeliIsTelefonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 140, 145, 30));

        jLabel23.setText("Ev telefonu");
        jLabel23.setName("gizle"); // NOI18N
        pnlVeliBilgileri.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 60, 30));

        jLabel24.setText("İş telefonu");
        jLabel24.setName("gizle"); // NOI18N
        pnlVeliBilgileri.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 70, 30));

        jLabel25.setText("Cep telefonu");
        jLabel25.setName("gizle"); // NOI18N
        pnlVeliBilgileri.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 70, 30));

        jLabel26.setText("Ev adresi");
        jLabel26.setName("gizle"); // NOI18N
        pnlVeliBilgileri.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 70, 30));

        jScrollPane1.setName("gizle"); // NOI18N

        txtVeliEvAdresi.setColumns(50);
        txtVeliEvAdresi.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtVeliEvAdresi.setLineWrap(true);
        txtVeliEvAdresi.setRows(5);
        txtVeliEvAdresi.setName("gizle"); // NOI18N
        jScrollPane1.setViewportView(txtVeliEvAdresi);

        pnlVeliBilgileri.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 200, 80));

        jLabel27.setText("<html>Öğrenim Durumu</html>");
        jLabel27.setName("gizle"); // NOI18N
        pnlVeliBilgileri.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 175, 50, 40));

        cbVeliOgrenimDurumu.setModel(new javax.swing.DefaultComboBoxModel<>(new Cift[] { new Cift(-1,"Öğrenim Durumu Seç")}));
        cbVeliOgrenimDurumu.setName("gizle"); // NOI18N
        cbVeliOgrenimDurumu.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cbVeliOgrenimDurumuActionPerformed(evt);
            }
        });
        pnlVeliBilgileri.add(cbVeliOgrenimDurumu, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 180, 145, 30));

        jScrollPane3.setName("gizle"); // NOI18N

        txtVeliIsAdresi.setColumns(50);
        txtVeliIsAdresi.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtVeliIsAdresi.setLineWrap(true);
        txtVeliIsAdresi.setRows(5);
        txtVeliIsAdresi.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtVeliIsAdresi.setName("gizle"); // NOI18N
        jScrollPane3.setViewportView(txtVeliIsAdresi);

        pnlVeliBilgileri.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 200, 80));

        jLabel29.setText("İş adresi");
        jLabel29.setName("gizle"); // NOI18N
        pnlVeliBilgileri.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 70, 30));

        jLabel43.setText("<html>Eposta Adresi</html>");
        jLabel43.setName("gizle"); // NOI18N
        pnlVeliBilgileri.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 60, 30));

        jLabel46.setText("Mesleği");
        jLabel46.setName("gizle"); // NOI18N
        pnlVeliBilgileri.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 70, 30));

        txtVeliCepTelefonu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtVeliCepTelefonu.setName("gizle"); // NOI18N
        pnlVeliBilgileri.add(txtVeliCepTelefonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 145, 30));

        txtVeliSoyadi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtVeliSoyadi.setName("elleme"); // NOI18N
        pnlVeliBilgileri.add(txtVeliSoyadi, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 60, 145, 30));

        txtVeliAdi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtVeliAdi.setName("elleme"); // NOI18N
        pnlVeliBilgileri.add(txtVeliAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 145, 30));

        txtVeliEvTelefonu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtVeliEvTelefonu.setName("gizle"); // NOI18N
        pnlVeliBilgileri.add(txtVeliEvTelefonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 145, 30));

        txtVeliEposta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtVeliEposta.setName("gizle"); // NOI18N
        pnlVeliBilgileri.add(txtVeliEposta, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 100, 145, 30));

        getContentPane().add(pnlVeliBilgileri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 450, 330));

        btnKaydet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnKaydet.setText("<html>Bilgileri  Kaydet</html>");
        btnKaydet.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnKaydetActionPerformed(evt);
            }
        });
        getContentPane().add(btnKaydet, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 100, 50));

        btnIptal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIptal.setText("İptal");
        btnIptal.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnIptalActionPerformed(evt);
            }
        });
        getContentPane().add(btnIptal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 100, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbVeliOgrenimDurumuActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbVeliOgrenimDurumuActionPerformed
    {//GEN-HEADEREND:event_cbVeliOgrenimDurumuActionPerformed
        // TODO add your handling code here:
        veliOgrenimDurumu=-1;
        if(cbVeliOgrenimDurumu.getSelectedIndex()>0)
        {
            veliOgrenimDurumu=((Cift)cbVeliOgrenimDurumu.getSelectedItem()).key;
            System.out.println(((Cift)cbVeliOgrenimDurumu.getSelectedItem()).value);
        }

    }//GEN-LAST:event_cbVeliOgrenimDurumuActionPerformed

    private void btnKaydetActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnKaydetActionPerformed
    {//GEN-HEADEREND:event_btnKaydetActionPerformed
        // TODO add your handling code here:
        ataPencere.velayet=new Veli();
        boolean islem=true;
        
        Locale trlocale= Locale.forLanguageTag("tr-TR");
        
        String hata="Hatalı Yapılan İşlemler";
        if(!(txtVeliAdi.getText().trim().matches("^[ığĞüÜşŞİöÖçÇa-zA-Z ]+$")))
        {
        islem=false;
        hata+="\n"+"* Lütfen Veli adı bilgisini doğru giriniz.";          

        }
        
        if(!(txtVeliSoyadi.getText().trim().matches("^[ığĞüÜşŞİöÖçÇa-zA-Z ]+$")))
        {
        islem=false;
        hata+="\n"+"* Lütfen Veli soyadı bilgisini doğru giriniz.";          

        }
      
        if(!(txtVeliMeslegi.getText().trim().matches("^[ığĞüÜşŞİöÖçÇa-zA-Z ]+$")))
        {
            islem=false;
            hata+="\n"+"* Lütfen Veli meslek bilgisini doğru giriniz.";          

        }
        if(!(txtVeliEposta.getText().trim().matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$")))
        {
            islem=false;
            hata+="\n"+"* Lütfen Veli eposta bilgisini doğru giriniz.";          

        }
          if(!(txtVeliEvAdresi.getText().trim().length()>6))
        {
            islem=false;
            hata+="\n"+"* Lütfen Veli ev adresi bilgisini doğru giriniz.";          

        }
         if(!(txtVeliCepTelefonu.getText().trim().matches("^[0][5]\\d{9}+$")))
        {
            islem=false;
            hata+="\n"+"* Lütfen Veli cep telefonu  bilgisini 05XXXXXXXXX şeklinde giriniz.";          

        }
        if(((Cift)cbVeliOgrenimDurumu.getSelectedItem()).key==-1)
        {
            islem=false;
            hata+="\n"+"* Lütfen Veli Öğrenim durumu bilgisini doğru giriniz.";
        }
         if(islem==false)
        {
            JOptionPane.showMessageDialog(rootPane, hata,"Hata",JOptionPane.ERROR_MESSAGE);
           // FotografiPaneleBas();
            return;
        }
        veliHayattami=1;
        veliAd=txtVeliAdi.getText().trim().toUpperCase(trlocale);
        veliSoyad=txtVeliSoyadi.getText().trim().toUpperCase(trlocale);
        veliCeptelefon=txtVeliCepTelefonu.getText();
        veliEposta=txtVeliEposta.getText().trim();
        veliEvAdresi=txtVeliEvAdresi.getText().trim().toUpperCase(trlocale);
        veliEvTelefon=txtVeliEvTelefonu.getText();
        veliIsTelefon=txtVeliIsTelefonu.getText();
        veliMeslegi=txtVeliMeslegi.getText().trim().toUpperCase(trlocale);
        veliIsAdresi=txtVeliIsAdresi.getText().trim().toUpperCase(trlocale);
        
        ataPencere.velayet.setCepTelefonu(veliCeptelefon);
        ataPencere.velayet.setEpostaAdresi(veliEposta);
        ataPencere.velayet.setEvAdresi(veliEvAdresi);
        ataPencere.velayet.setEvTelefonu(veliEvTelefon);
        ataPencere.velayet.setHayattami(veliHayattami);
        ataPencere.velayet.setIsAdresi(veliIsAdresi);
        ataPencere.velayet.setIsTelefonu(veliIsTelefon);
        ataPencere.velayet.setMeslegi(veliMeslegi);
        ataPencere.velayet.setOgrenimDurumu(new OgrenimDurumu(veliOgrenimDurumu,((Cift)cbVeliOgrenimDurumu.getSelectedItem()).value));
        ataPencere.velayet.setVeliAdi(veliAd);
        ataPencere.velayet.setVeliSoyadi(veliSoyad);
        ataPencere.velayet.setVeliTipi(new VeliTipi(veliTipi));
        this.dispose();
            
        
    }//GEN-LAST:event_btnKaydetActionPerformed

    private void btnIptalActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnIptalActionPerformed
    {//GEN-HEADEREND:event_btnIptalActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnIptalActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        // TODO add your handling code here:
        OgrenimDurumuCBDoldur();
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VeliBilgisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VeliBilgisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VeliBilgisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VeliBilgisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VeliBilgisi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIptal;
    private javax.swing.JButton btnKaydet;
    private javax.swing.JComboBox<Cift> cbVeliOgrenimDurumu;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel pnlVeliBilgileri;
    private javax.swing.JTextField txtVeliAdi;
    private javax.swing.JTextField txtVeliCepTelefonu;
    private javax.swing.JTextField txtVeliEposta;
    private javax.swing.JTextArea txtVeliEvAdresi;
    private javax.swing.JTextField txtVeliEvTelefonu;
    private javax.swing.JTextArea txtVeliIsAdresi;
    private javax.swing.JTextField txtVeliIsTelefonu;
    private javax.swing.JTextField txtVeliMeslegi;
    private javax.swing.JTextField txtVeliSoyadi;
    // End of variables declaration//GEN-END:variables
}
